ATTENDANCE_COLS = [
    "email_clean",
    "Webinar Date",
    "Webinar ID",
    "Attended",
    "Registration Time",
]

PEOPLE_COLS = [
    # Key
    "email_clean",
    # Webinar profile / identity fields
    "First Name",
    "Last Name",
    "Email",
    "Zip/Postal Code",
    "State/Province",
    "Industry",
    "Organization",
    "Number of Employees",
    "Country/Region Name",
    "Source Name",
    # Matching key
    "full_name_clean",
    # NeoSerra / client fields
    "Client?",
    "NS Client ID",
    "NS Client",
    "NS Primary Contact",
    "NS Last Counseling",
    "NS Phone",
    "NS Email",
    "NS Center",
    "NS Center Abbr",
    "NS Client/Pre-client Type",
    "NS Address",
    "NS ZIP Code",
    "NS Match Type",
    # Location Data and Center Assignment for Non Clients
    "Zip Problem",
    "Assigned Center Abbr",
    "Assigned Center Name",
    "Missing Center",
    "Needs Center Review",
]

NEOSERRA_COLUMNS = [
    "Client ID",
    "Client",
    "Primary Contact",
    "Last Counseling",
    "Phone",
    "Email",
    "Email Address",
    "Center",
    "Client/Pre-client Type",
    "Physical Address",
    "Physical Address ZIP Code",
]


NS_OUTPUT_COLUMNS = [
    "Client ID",
    "Client",
    "Primary Contact",
    "Last Counseling",
    "Phone",
    "Email",
    "Center",
    "Center Abbr",
    "Client/Pre-client Type",
    "Physical Address",
    "Physical Address ZIP Code",
    "email_clean",
    "full_name_clean",
]

NS_RENAME_COLS = {
    "attended": "Attended",
    "is_client": "Client?",
    "Client ID": "NS Client ID",
    "Email_ns": "NS Email",
    "Client": "NS Client",
    "Primary Contact": "NS Primary Contact",
    "Last Counseling": "NS Last Counseling",
    "Phone": "NS Phone",
    "Center": "NS Center",
    "Center Abbr": "NS Center Abbr",
    "Client/Pre-client Type": "NS Client/Pre-client Type",
    "Physical Address": "NS Address",
    "Physical Address ZIP Code": "NS ZIP Code",
    "ns_match_source": "NS Match Type",
    "webinar_id": "Webinar ID",
    "webinar_date": "Webinar Date",
}

WEBINAR_KEEP_COLS = [
    "Attended",
    "First Name",
    "Last Name",
    "Email",
    "Zip/Postal Code",
    "State/Province",
    "Industry",
    "Organization",
    "Number of Employees",
    "Registration Time",
    "Country/Region Name",
    "Source Name",
]

FINAL_KEEP_COLS = [
    "Client?",
    "Attended",
    "Webinar ID",
    "Webinar Date",
    "First Name",
    "Last Name",
    "Email",
    "Zip/Postal Code",
    "State/Province",
    "Industry",
    "Organization",
    "Number of Employees",
    "Registration Time",
    "Country/Region Name",
    "Source Name",
    "email_clean",
    "full_name_clean",
    "NS Client ID",
    "NS Client",
    "NS Primary Contact",
    "NS Last Counseling",
    "NS Phone",
    "NS Email",
    "NS Center",
    "NS Center Abbr",
    "NS Client/Pre-client Type",
    "NS Address",
    "NS ZIP Code",
    "NS Match Type",
]


ZIP_MERGE_KEEP_COLS = [
    "Client?",
    "NS Client ID",
    "Email",
    "First Name",
    "Last Name",
    "Industry",
    "Organization",
    "Number of Employees",
    "Source Name",
    "Registration Time",
    "Assigned Center Abbr",
    "Assigned Center Name",
    "Missing Center",
    "Zip/Postal Code",
    "State/Province",
    "Zip Problem",
    "NS Primary Contact",
    "NS Center",
    "NS Center Abbr",
    "NS Client",
    "NS Client/Pre-client Type",
    "NS Email",
    "NS Last Counseling",
    "NS Match Type",
    "NS Phone",
]
